name: fitness_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  flutter_svg: ^1.1.1+1
  dots_indicator: ^2.1.0

  firebase_core: ^1.20.0
  firebase_auth: ^3.5.1
  firebase_analytics: ^9.3.0
  cloud_firestore: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
